services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  # Database Mangement interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080